# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 08:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='\u90ae\u7bb1')),
                ('is_kyc', models.BooleanField(default=False, verbose_name='KYC \u72b6\u6001')),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_kyc', models.TextField(blank=True, null=True, verbose_name='KYC \u72b6\u6001')),
                ('eth_wallet', models.TextField(blank=True, null=True, verbose_name='ETH \u94b1\u5305')),
                ('invests', models.TextField(blank=True, null=True, verbose_name='\u6295\u8d44')),
                ('fullname', models.TextField(blank=True, null=True, verbose_name='\u5168\u540d')),
                ('password', models.TextField(blank=True, null=True, verbose_name='\u5bc6\u7801')),
                ('invite_code', models.IntegerField(blank=True, null=True, verbose_name='\u9080\u8bf7\u7801')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
